### ISSUE TITLE
Code runs in O(n^2)

### ISSUE THREAD

**Issue by vbanurag** [RavinduThaveesha/algorithm#1]
Because JS array.includes runs in O(n^2) for further you can verify here https://tc39.es/ecma262/#sec-array.prototype.includes

or you can use SET or map to achieve O(n)

below code in O(n)

`
function checkDuplicate (array) {
  let tmp = {};
  for (i = 0; i < array.length; i++) {
    if (tmp[array[i]]) {
      return array[i];
    } else {
      tmp[array[i]] = array[i]
    }
  }
  
  return -1;
}

`

**Comment by RavinduThaveesha** [comment]
Yeah thanks for pointing out.
